### ISSUE TITLE
Proposal feedback

### ISSUE THREAD

**Issue by hsmohammed** [UBC-MDS/AutoTransformR#1]
Hello,
Thank you for the great effort. I just have some suggestions below,
1- You are only required to do 3 functions in the package, so if you think limiting your functions to only 3 will save you time then consider that.
2- You can give the users more control over the image editing parameters. For example, giving the user the choice to enter the parameters themselves besides the option to generate a number of modified images with random parameters.
Thanks!

**Comment by everittB** [comment]
1. Selected three functions to develop 
2. Given user controls with parameters for the number of images to generate and how much to rotate/translate them
