### ISSUE TITLE
Final Submission Requirements

### ISSUE THREAD

**Issue by everittB** [UBC-MDS/AutoTransformR#23]
- [X] Appropriate exception handlers  
-  ~~Integration testing, if applicable~~  
- [x] Continuous integration using `Travis`  
  - [x] Passing build stamp on `README`  
- Instructions of package use on `README`   
  - [x] Installation/setup of package  
  - [x] Calling functions   
  - [x] Example (outputs)

**Comment by everittB** [comment]
Pull Request: #24

**Comment by everittB** [comment]
- On the `README` is looks like the Travis build status is looking at the `admin` branch and not the master

**Comment by alyciakb** [comment]
> * On the `README` is looks like the Travis build status is looking at the `admin` branch and not the master

Changed to the `master` branch in Pull request: #25

**Comment by everittB** [comment]
Added in exception handling, pull request #26
